export const TOMTOM_API_KEY = process.env.EXPO_PUBLIC_TOMTOM_API_KEY

export const ENCRYPT_STORAGE = process.env.EXPO_PUBLIC_ENCRYPT_STORAGE

export const ONESIGNAL_APP_ID = process.env.EXPO_PUBLIC_ONESIGNAL_APP_ID
